apiVersion: v1
kind: PersistentVolume
metadata:
  name: akhq
  labels:
    app: akhq-cluster
akhq:
  connections:
    app-messaging:
      properties:
        bootstrap.servers: kafka-service:9092,kafka-service:29092
        security.protocol: SSL
        ssl.truststore.location: /usr/local/openjdk-11/lib/security/cacerts
        ssl.truststore.password: 
      