apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: akhq
  name: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: akhq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: akhq
    spec:
      containers:
        - env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    kafka:
                      properties:
                        bootstrap.servers: "kafka-service:9092"
          image: tchiotludo/akhq
          name: akhq
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}