apiVersion: v1
kind: Service
metadata:
  name: akhq-cluster
spec:
  selector:
    app: akhq-cluster
  type: LoadBalancer
  ports:
  - name: client
    port: 8080
    targetPort: 8080
  - name: follower
    port: 8081
    targetPort: 8081
  - name: leader
    port: 8082
    targetPort: 8082
     

apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
        app: akhq-cluster
  template:
    metadata:
      labels:
        app: akhq-cluster
    spec:
      hostname: akhq-cluster
      containers:
      - name: akhq-cluster
        image: tchiotludo/akhq:0.18.0 
#        image: bitnami/kafka:latest
        resources:
          requests:
            memory: "1G"
            cpu: "1"             
        ports:
         - containerPort: 8080
        env:
         - name: AKHQ_CFH_KAFKA_CONNECT
           value: kafka-broker:9092
