apiVersion: v1
kind: Service
metadata:
  name: akhq-service
spec:
  selector:
    app: akhq-cluster
  ports:
  - port: 8080
    targetPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq-cluster
spec:
  selector:
    matchLabels:
      app: akhq-cluster
  template:
    metadata:
      labels:
        app: akhq-cluster
    spec:
      containers:
      - name: akhq-cluster
        image: tchiotludo/akhq:0.18.0 
        ports:
        - containerPort: 8080


