apiVersion: v1
kind: Pod
metadata:
  name: test

spec:
  containers:
    - name: test
      image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
      env:
        - name: POSTGRES_CONNECTION
          value: "postgresql://postgres-service:5432/pimp"
      command:
        - /bin/bash
        - -ec
        -
                    psql -d $POSTGRES_CONNECTION -U kisrobert --password -parola
  restartPolicy: Never